### PR TITLE
Issue-46 Updated MjpegFileWriter.java and removed commented-out-line

### PR DESCRIPTION
**Pull request by istiaqahmed121998**

### CODE REVIEW

**Review by hanif-ali — APPROVED** [review]
Looks good. It looks like the previous declarations were replaced but the older code was never removed.

**Review by istiaqahmed121998 — COMMENTED** [review]
I removed these commented-out-lines

**Comment by hanif-ali** [comment]
@istiaqahmed121998 yes, you can merge it

**Review by istiaqahmed121998 — COMMENTED** [review]
Final merge.

**Pull request merged**
